# Generated by Django 2.0.3 on 2018-04-01 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('anime_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=300)),
                ('typeAnime', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('members', models.IntegerField()),
                ('anime_cover', models.ImageField(blank=True, null=True, upload_to='img/animeCover', verbose_name='Profile Photo')),
            ],
        ),
    ]
