# Generated by Django 2.0.3 on 2018-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180401_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animecatalog',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='animecatalog',
            old_name='typeAnime',
            new_name='typeanime',
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
