# Generated by Django 2.0.3 on 2018-04-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180402_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecatalog',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
