# Generated by Django 2.0.3 on 2018-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180404_0116'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='animecatalog',
            name='anime_url',
            field=models.CharField(default='{% static "img/imgNotFound.jpg" %}', max_length=300),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='anime_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
