# Generated by Django 2.0.3 on 2018-04-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180405_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animecatalog',
            name='anime_cover',
        ),
    ]
