# Generated by Django 2.0.3 on 2018-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_animecatalog_anime_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='anime_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
