# Generated by Django 2.0.3 on 2018-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180405_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='anime_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
