# Generated by Django 2.0.3 on 2018-04-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180405_1716'),
    ]

    operations = [
    ]
