# Generated by Django 2.0.3 on 2018-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180405_1855'),
    ]

    operations = [
    ]
