# Generated by Django 2.0.3 on 2018-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_animecatalog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='episodes',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='genre',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='members',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='rating',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='typeanime',
            field=models.CharField(default='', max_length=10),
        ),
    ]
