# Generated by Django 2.0.3 on 2018-04-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180405_1924'),
    ]

    operations = [
    ]
