# Generated by Django 2.0.3 on 2018-04-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_animecatalog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='anime_url',
            field=models.CharField(blank=True, default='{% static "img/imgNotFound.jpg" %}', max_length=300),
        ),
    ]
