# Generated by Django 2.0.3 on 2018-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180405_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='anime_url',
            field=models.CharField(blank=True, default='{% static "img/imgNotFound.jpg" %}', max_length=300, null=True),
        ),
    ]
