# Generated by Django 2.0.3 on 2018-04-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180405_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='anime_url',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
